
[functions.telnyx-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/telnyx-webhook/deno.json"
entrypoint = "./functions/telnyx-webhook/index.ts"

[functions.telnyx-call]
enabled = true
verify_jwt = false
entrypoint = "./functions/telnyx-call/index.ts"

[functions.telnyx-hangup]
enabled = true
verify_jwt = true
entrypoint = "./functions/telnyx-hangup/index.ts"

[functions.telnyx-push-kyc-document]
enabled = true
verify_jwt = false
entrypoint = "./functions/telnyx-push-kyc-document/index.ts"

[functions.telnyx-upload-document]
enabled = true
verify_jwt = false
entrypoint = "./functions/telnyx-upload-document/index.ts"

[functions.telnyx-get-requirements]
enabled = true
verify_jwt = false
entrypoint = "./functions/telnyx-get-requirements/index.ts"

[functions.telnyx-sync-numbers]
enabled = true
verify_jwt = false
entrypoint = "./functions/telnyx-sync-numbers/index.ts"

[functions.telnyx-buy-number]
enabled = true
verify_jwt = false
entrypoint = "./functions/telnyx-buy-number/index.ts"

[functions.telnyx-search-numbers]
enabled = true
verify_jwt = false
entrypoint = "./functions/telnyx-search-numbers/index.ts"

[functions.telnyx-list-numbers]
enabled = true
verify_jwt = false
entrypoint = "./functions/telnyx-list-numbers/index.ts"

[functions.telnyx-fulfill-and-order]
enabled = true
verify_jwt = false
entrypoint = "./functions/telnyx-fulfill-and-order/index.ts"

[functions.assign-number-to-agent]
enabled = true
verify_jwt = false
entrypoint = "./functions/assign-number-to-agent/index.ts"

[functions.telnyx-push-agent]
enabled = true
verify_jwt = false
import_map = "./functions/telnyx-push-agent/deno.json"
entrypoint = "./functions/telnyx-push-agent/index.ts"

[functions.ai-call-insights]
enabled = true
verify_jwt = false
entrypoint = "./functions/ai-call-insights/index.ts"

[functions.telnyx-embed-url]
enabled = true
verify_jwt = false
entrypoint = "./functions/telnyx-embed-url/index.ts"

[functions.telnyx-embed-document]
enabled = true
verify_jwt = false
entrypoint = "./functions/telnyx-embed-document/index.ts"
